
version: '3'
services:
  frontend-service:
    build: ./src/frontend-service
    image: frontend-service
    ports:
      - "5000:5000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5003
      - WEATHER_SERVICE_URL=http://weather-service:5001
      - RECOMMENDATION_SERVICE_URL=http://recommendation-service:5002
  
  auth-service:
    build: ./src/auth-service
    image: auth-service
    ports:
      - "5003:5003"
  
  weather-service:
    build: ./src/weather-service
    image: weather-service
    ports:
      - "5001:5001"
  
  recommendation-service:
    build: ./src/recommendation-service
    image: recommendation-service
    ports:
      - "5002:5002"

networks:
  default:
    name: weather-app-network
